[package]
name = "TaskBot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
serde = "1.0.228"
serde_json = "1.0.149"
serenity = "0.12.5"
sqlx = "0.8.6"
tokio = { version="1.49.0", features=["full"]}
